---
title: "get_encorafenib_data"
author: "Ursula Widocki"
date: "2025-05-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(magrittr)
```

# Read in downloads
```{r}
# Downloaded from the MTS_SEQ004_B40_COMPOUNDS Downloads page on the PRISM portal

norm_counts <- data.table::fread("~/Desktop/data/vignette_test_data/src/MTS_SEQ004_B40_COMPOUNDS_normalized_counts.csv")
l2fc <- data.table::fread("~/Desktop/data/vignette_test_data/src/MTS_SEQ004_B40_COMPOUNDS_l2fc.csv")
collapsed_l2fc <- data.table::fread("~/Desktop/data/vignette_test_data/src/MTS_SEQ004_B40_COMPOUNDS_collapsed_l2fc.csv")
```

# Filter for encorafenib
```{r}
filter_counts <- norm_counts %>% select(-cb_intercept, -log2_normalized_n)
norm_counts %<>% filter(pert_name == "ENCORAFENIB" | pert_type %in% c("ctl_vehicle", "trt_poscon"))
l2fc %<>% filter(pert_name == "ENCORAFENIB")
collapsed_l2fc %<>% filter(pert_name == "ENCORAFENIB")

CB_meta <- norm_counts %>% select(cb_name, cb_log2_dose, cb_ladder)
```

# Write data into new folders
```{r}
write.csv(filter_counts, "~/Desktop/data/vignette_test_data/data/filtered_counts.csv", row.names = F)
write.csv(norm_counts, "~/Desktop/data/vignette_test_data/data/normalized_counts.csv", row.names = F)
write.csv(l2fc, "~/Desktop/data/vignette_test_data/data/l2fc.csv", row.names = F)
write.csv(collapsed_l2fc, "~/Desktop/data/vignette_test_data/data/collapsed_l2fc.csv", row.names = F)
write.csv(CB_meta, "~/Desktop/data/vignette_test_data/data/CB_meta.csv", row.names = F)
```


