---
title: "testing_norm_example"
author: "Ursula Widocki"
date: "2025-05-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set up this environment
```{r}
library(tidyverse)
library(magrittr)
```

# Code on vignette
```{r example normalization, echo = T, eval = F}
# Load into environment ----
require(magrittr)
require(tidyverse)
source("~/sushi/scripts/utils/kitchen_utensils.R")
source("~/sushi/scripts/normalilze/normalize_functions.R")

# Set up inputs ----
filtered_counts <- data.table::fread("~/Desktop/data/vignette_test_data/data/filtered_counts.csv")
CB_meta <- data.table::fread("~/Desktop/data/vignette_test_data/data/CB_meta.csv")
pseudocount <- 20
input_id_cols <- c("pcr_plate", "pcr_well")

# Normalize your counts ----
normalized_counts = normalize(X = filtered_counts, 
                              id_cols = input_id_cols,
                              CB_meta = CB_meta, 
                              pseudocount = pseudocount)

```
