---
title: "testing_drc_example"
author: "Ursula Widocki"
date: "2025-05-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Example

```{r example drc, echo = T, eval = F}
# Load into environment ----
require(magrittr)
require(tidyverse)
library(drc)
source("~/Desktop/sushi/scripts/utils/kitchen_utensils.R")
source("~/Desktop/sushi/scripts/drc/dose_response_functions.R")

# Set up inputs ----
l2fc <- data.table::fread("~/Desktop/data/vignette_test_data/data/l2fc.csv")
cell_line_cols <- c("depmap_id", "lua", "pool_id")
sig_cols <- c("cell_set","pert_name","pert_dose","pert_dose_unit","day")
dose_col <- "pert_dose"
l2fc_column <- "l2fc"
type_col <- "pert_type"
cap_for_viability <- 1.5

# Create treatment_columns by removing column names containing "dose" ----
treatment_cols <- union(
  sig_cols[grepl("pert", sig_cols) & !grepl("dose", sig_cols)],
  sig_cols[sig_cols == "day"]
)

# FIT DRC curves ----
dose_response= create_drc_table(LFC= l2fc,
                                cell_line_cols= cell_line_cols,
                                treatment_cols= treatment_cols,
                                dose_col= dose_col,
                                l2fc_column= l2fc_column,
                                type_col= type_col,
                                cap_for_viability= cap_for_viability)

```

# Plot 
```{r}
drc_cell_line_example <- dose_response %>% filter(depmap_id == "ACH-000020")

dose <- drc_cell_line_example$minimum_dose * 3^(0:5)
lower_lim <- drc_cell_line_example$lower_limit
upper_lim <- drc_cell_line_example$upper_limit
ec50 <- drc_cell_line_example$inflection
slope <- drc_cell_line_example$slope

response <- upper_lim + ((lower_lim - upper_lim) / (1 + (dose/ec50)^slope))

df <- data.frame(dose, response)

drc_plot <- ggplot(df, aes(x = dose, y = response)) +
  geom_line(color = "blue") +
  geom_point() +
  scale_x_log10() +
  geom_vline(xintercept = ec50, linetype = "dashed", color = "red") +
  labs(title = "3-Fold Dose-Response Curve", x = "Dose (log10 scale)", y = "Response") +
  theme_minimal()

print(drc_plot)
```

